-- ==============================================================================
-- SHREE AURA COTTONS - DATABASE SCHEMA (CLEARED)
-- ==============================================================================
-- All previous SQL table queries have been cleared as requested.
