-- ==============================================================================
-- SHREE AURA COTTONS - SUPABASE DATABASE SCHEMA (AUG 22 VERSION)
-- ==============================================================================
-- Run this complete script in Supabase SQL Editor (SQL Editor -> New Query -> Run)

-- 1. EXTENSIONS
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- 2. DROP PREVIOUS TABLES (Clean slate)
DROP TABLE IF EXISTS public.order_items CASCADE;
DROP TABLE IF EXISTS public.orders CASCADE;
DROP TABLE IF EXISTS public.wishlist CASCADE;
DROP TABLE IF EXISTS public.product_images CASCADE;
DROP TABLE IF EXISTS public.products CASCADE;
DROP TABLE IF EXISTS public.categories CASCADE;
DROP TABLE IF EXISTS public.profiles CASCADE;

-- 3. TABLES DEFINITIONS

-- CATEGORIES TABLE (Sequential IDs: 1, 2, 3...)
CREATE TABLE public.categories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    slug VARCHAR(100) UNIQUE NOT NULL,
    description TEXT,
    image_url TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- PRODUCTS TABLE (Product ID = Product Code, e.g., 'SAR-COT-001')
CREATE TABLE public.products (
    id VARCHAR(100) PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    slug VARCHAR(255) UNIQUE NOT NULL,
    description TEXT,
    category_id BIGINT REFERENCES public.categories(id) ON DELETE SET NULL,
    price DECIMAL(10,2) NOT NULL,
    compare_price DECIMAL(10,2),
    discount_percentage INT DEFAULT 0,
    fabric VARCHAR(100),
    color VARCHAR(100),
    occasion VARCHAR(100),
    stock INT DEFAULT 0,
    sku VARCHAR(100) UNIQUE NOT NULL,
    main_image TEXT NOT NULL,
    is_active BOOLEAN DEFAULT TRUE,
    is_featured BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- PRODUCT IMAGES GALLERY TABLE
CREATE TABLE public.product_images (
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    product_id VARCHAR(100) REFERENCES public.products(id) ON DELETE CASCADE,
    image_url TEXT NOT NULL,
    display_order INT DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- USER PROFILES TABLE (Linked to Supabase auth.users UUID)
CREATE TABLE public.profiles (
    id UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
    full_name VARCHAR(255),
    phone VARCHAR(20),
    role VARCHAR(20) DEFAULT 'customer' CHECK (role IN ('customer', 'admin')),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- WISHLIST TABLE
CREATE TABLE public.wishlist (
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
    product_id VARCHAR(100) REFERENCES public.products(id) ON DELETE CASCADE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    UNIQUE(user_id, product_id)
);

-- ORDERS TABLE (Sequential Order Numbers starting at 10001)
CREATE TABLE public.orders (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 10001 INCREMENT BY 1) PRIMARY KEY,
    user_id UUID REFERENCES auth.users(id) ON DELETE SET NULL,
    customer_name VARCHAR(255) NOT NULL,
    phone VARCHAR(20) NOT NULL,
    email VARCHAR(255) NOT NULL,
    address TEXT NOT NULL,
    city VARCHAR(100) NOT NULL,
    state VARCHAR(100) NOT NULL,
    pincode VARCHAR(10) NOT NULL,
    total_amount DECIMAL(10,2) NOT NULL,
    payment_status VARCHAR(50) DEFAULT 'pending' CHECK (payment_status IN ('pending', 'paid', 'failed')),
    order_status VARCHAR(50) DEFAULT 'placed' CHECK (order_status IN ('placed', 'processing', 'shipped', 'delivered', 'cancelled')),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- ORDER ITEMS TABLE
CREATE TABLE public.order_items (
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    order_id BIGINT REFERENCES public.orders(id) ON DELETE CASCADE,
    product_id VARCHAR(100) REFERENCES public.products(id) ON DELETE SET NULL,
    product_name VARCHAR(255) NOT NULL,
    quantity INT NOT NULL CHECK (quantity > 0),
    price DECIMAL(10,2) NOT NULL,
    subtotal DECIMAL(10,2) NOT NULL
);

-- 4. PERFORMANCE INDEXES
CREATE INDEX idx_products_category ON public.products(category_id);
CREATE INDEX idx_products_fabric ON public.products(fabric);
CREATE INDEX idx_products_color ON public.products(color);
CREATE INDEX idx_products_occasion ON public.products(occasion);
CREATE INDEX idx_products_price ON public.products(price);
CREATE INDEX idx_products_active ON public.products(is_active);
CREATE INDEX idx_orders_user ON public.orders(user_id);
CREATE INDEX idx_wishlist_user ON public.wishlist(user_id);

-- 5. PROFILE TRIGGER ON USER SIGNUP
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS TRIGGER AS $$
BEGIN
  INSERT INTO public.profiles (id, full_name, phone, role)
  VALUES (
    new.id,
    COALESCE(new.raw_user_meta_data->>'full_name', 'Customer'),
    COALESCE(new.raw_user_meta_data->>'phone', ''),
    COALESCE(new.raw_user_meta_data->>'role', 'customer')
  )
  ON CONFLICT (id) DO NOTHING;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE FUNCTION public.handle_new_user();

-- 6. PERMISSIONS & ACCESS CONTROL (Guarantees public order placement works)
ALTER TABLE public.categories DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.products DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.product_images DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.orders DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.order_items DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.wishlist DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.profiles DISABLE ROW LEVEL SECURITY;

GRANT ALL ON public.categories TO anon, authenticated, service_role;
GRANT ALL ON public.products TO anon, authenticated, service_role;
GRANT ALL ON public.product_images TO anon, authenticated, service_role;
GRANT ALL ON public.orders TO anon, authenticated, service_role;
GRANT ALL ON public.order_items TO anon, authenticated, service_role;
GRANT ALL ON public.wishlist TO anon, authenticated, service_role;
GRANT ALL ON public.profiles TO anon, authenticated, service_role;

DROP POLICY IF EXISTS "Public Orders Insert" ON public.orders;
CREATE POLICY "Public Orders Insert" ON public.orders FOR INSERT WITH CHECK (true);

DROP POLICY IF EXISTS "Public Orders Select" ON public.orders;
CREATE POLICY "Public Orders Select" ON public.orders FOR SELECT USING (true);

DROP POLICY IF EXISTS "Public Orders Update" ON public.orders;
CREATE POLICY "Public Orders Update" ON public.orders FOR UPDATE USING (true);

DROP POLICY IF EXISTS "Public Order Items Insert" ON public.order_items;
CREATE POLICY "Public Order Items Insert" ON public.order_items FOR INSERT WITH CHECK (true);

DROP POLICY IF EXISTS "Public Order Items Select" ON public.order_items;
CREATE POLICY "Public Order Items Select" ON public.order_items FOR SELECT USING (true);

-- 7. SUPABASE STORAGE BUCKET CONFIGURATION FOR PRODUCT IMAGES
INSERT INTO storage.buckets (id, name, public)
VALUES ('product-images', 'product-images', true)
ON CONFLICT (id) DO UPDATE SET public = true;

DROP POLICY IF EXISTS "Public Access product-images" ON storage.objects;
CREATE POLICY "Public Access product-images" ON storage.objects
FOR SELECT USING (bucket_id = 'product-images');

DROP POLICY IF EXISTS "Public Insert product-images" ON storage.objects;
CREATE POLICY "Public Insert product-images" ON storage.objects
FOR INSERT WITH CHECK (bucket_id = 'product-images');

DROP POLICY IF EXISTS "Public Update product-images" ON storage.objects;
CREATE POLICY "Public Update product-images" ON storage.objects
FOR UPDATE USING (bucket_id = 'product-images');

-- 8. INITIAL CATEGORIES ONLY (ZERO DUMMY PRODUCTS - READY FOR ADMIN ENTRY)
INSERT INTO public.categories (name, slug, description, image_url) VALUES
('Wedding Sarees', 'wedding-sarees', 'Opulent Kanchipuram & Banarasi bridal heirloom collections.', ''),
('Office Wear', 'office-wear', 'Elegantly styled, comfortable handloom sarees engineered for professional wear.', ''),
('Daily Wear', 'daily-wear', 'Lightweight, elegant, everyday sarees engineered for comfort.', '')
ON CONFLICT (slug) DO NOTHING;
