-- ==============================================================================
-- SHREE AURA COTTONS - SUPABASE DATABASE SCHEMA (CLIENT PURPOSE FORMAT)
-- ==============================================================================
-- Features:
-- 1. Sequential Integer IDs (1, 2, 3...) for Categories, Product Images, Wishlist, Order Items
-- 2. Human-Readable Order IDs starting from 10000 Series (10001, 10002, 10003...)
-- 3. Product Code (e.g. 'SAR-COT-001') as Primary Product ID
-- ==============================================================================

-- 1. CLEANUP PREVIOUS TABLES (If re-running)
DROP TABLE IF EXISTS public.order_items CASCADE;
DROP TABLE IF EXISTS public.orders CASCADE;
DROP TABLE IF EXISTS public.wishlist CASCADE;
DROP TABLE IF EXISTS public.product_images CASCADE;
DROP TABLE IF EXISTS public.products CASCADE;
DROP TABLE IF EXISTS public.categories CASCADE;
DROP TABLE IF EXISTS public.profiles CASCADE;

-- 2. TABLE DEFINITIONS

-- CATEGORIES TABLE (Sequential Integer ID)
CREATE TABLE public.categories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1) PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    slug VARCHAR(100) UNIQUE NOT NULL,
    description TEXT,
    image_url TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- PRODUCTS TABLE (Product Code / SKU as Primary Product ID)
CREATE TABLE public.products (
    id VARCHAR(100) PRIMARY KEY, -- e.g. 'SAR-COT-001'
    name VARCHAR(255) NOT NULL,
    slug VARCHAR(255) UNIQUE NOT NULL,
    description TEXT,
    category_id BIGINT REFERENCES public.categories(id) ON DELETE SET NULL,
    price DECIMAL(10,2) NOT NULL,
    compare_price DECIMAL(10,2),
    discount_percentage INT DEFAULT 0,
    fabric VARCHAR(100),
    color VARCHAR(100),
    occasion VARCHAR(100),
    stock INT DEFAULT 0,
    sku VARCHAR(100) UNIQUE NOT NULL,
    main_image TEXT NOT NULL,
    is_active BOOLEAN DEFAULT TRUE,
    is_featured BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- PRODUCT IMAGES GALLERY TABLE
CREATE TABLE public.product_images (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1) PRIMARY KEY,
    product_id VARCHAR(100) REFERENCES public.products(id) ON DELETE CASCADE,
    image_url TEXT NOT NULL,
    display_order INT DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- USER PROFILES TABLE (Linked to Supabase auth.users)
CREATE TABLE public.profiles (
    id UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
    full_name VARCHAR(255),
    phone VARCHAR(20),
    role VARCHAR(20) DEFAULT 'customer' CHECK (role IN ('customer', 'admin')),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- WISHLIST TABLE
CREATE TABLE public.wishlist (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1) PRIMARY KEY,
    user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
    product_id VARCHAR(100) REFERENCES public.products(id) ON DELETE CASCADE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    UNIQUE(user_id, product_id)
);

-- ORDERS TABLE (Sequential ID starting from 10000 Series: 10001, 10002, 10003...)
CREATE TABLE public.orders (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 10001) PRIMARY KEY,
    user_id UUID REFERENCES auth.users(id) ON DELETE SET NULL,
    customer_name VARCHAR(255) NOT NULL,
    phone VARCHAR(20) NOT NULL,
    email VARCHAR(255) NOT NULL,
    address TEXT NOT NULL,
    city VARCHAR(100) NOT NULL,
    state VARCHAR(100) NOT NULL,
    pincode VARCHAR(10) NOT NULL,
    total_amount DECIMAL(10,2) NOT NULL,
    payment_status VARCHAR(50) DEFAULT 'pending' CHECK (payment_status IN ('pending', 'paid', 'failed')),
    order_status VARCHAR(50) DEFAULT 'placed' CHECK (order_status IN ('placed', 'processing', 'shipped', 'delivered', 'cancelled')),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- ORDER ITEMS TABLE
CREATE TABLE public.order_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1) PRIMARY KEY,
    order_id BIGINT REFERENCES public.orders(id) ON DELETE CASCADE,
    product_id VARCHAR(100) REFERENCES public.products(id) ON DELETE SET NULL,
    product_name VARCHAR(255) NOT NULL,
    quantity INT NOT NULL CHECK (quantity > 0),
    price DECIMAL(10,2) NOT NULL,
    subtotal DECIMAL(10,2) NOT NULL
);

-- 3. INDEXES FOR PERFORMANCE
CREATE INDEX idx_products_category ON public.products(category_id);
CREATE INDEX idx_products_fabric ON public.products(fabric);
CREATE INDEX idx_products_color ON public.products(color);
CREATE INDEX idx_products_occasion ON public.products(occasion);
CREATE INDEX idx_products_price ON public.products(price);
CREATE INDEX idx_products_active ON public.products(is_active);
CREATE INDEX idx_orders_user ON public.orders(user_id);
CREATE INDEX idx_wishlist_user ON public.wishlist(user_id);

-- 4. PROFILE CREATION TRIGGER ON SIGNUP
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS TRIGGER AS $$
BEGIN
  INSERT INTO public.profiles (id, full_name, phone, role)
  VALUES (
    new.id,
    COALESCE(new.raw_user_meta_data->>'full_name', 'Customer'),
    COALESCE(new.raw_user_meta_data->>'phone', ''),
    COALESCE(new.raw_user_meta_data->>'role', 'customer')
  )
  ON CONFLICT (id) DO NOTHING;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE FUNCTION public.handle_new_user();

-- 5. ACCESS CONTROL & PERMISSIONS (For seamless storefront order placement)
ALTER TABLE public.categories DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.products DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.product_images DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.orders DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.order_items DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.wishlist DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.profiles DISABLE ROW LEVEL SECURITY;

GRANT ALL ON public.categories TO anon, authenticated, service_role;
GRANT ALL ON public.products TO anon, authenticated, service_role;
GRANT ALL ON public.product_images TO anon, authenticated, service_role;
GRANT ALL ON public.orders TO anon, authenticated, service_role;
GRANT ALL ON public.order_items TO anon, authenticated, service_role;
GRANT ALL ON public.wishlist TO anon, authenticated, service_role;
GRANT ALL ON public.profiles TO anon, authenticated, service_role;

-- 6. STORAGE BUCKET INITIALIZATION
INSERT INTO storage.buckets (id, name, public)
VALUES ('product-images', 'product-images', true)
ON CONFLICT (id) DO UPDATE SET public = true;

DROP POLICY IF EXISTS "Public Access product-images" ON storage.objects;
CREATE POLICY "Public Access product-images" ON storage.objects
FOR SELECT USING (bucket_id = 'product-images');

DROP POLICY IF EXISTS "Public Insert product-images" ON storage.objects;
CREATE POLICY "Public Insert product-images" ON storage.objects
FOR INSERT WITH CHECK (bucket_id = 'product-images');

DROP POLICY IF EXISTS "Public Update product-images" ON storage.objects;
CREATE POLICY "Public Update product-images" ON storage.objects
FOR UPDATE USING (bucket_id = 'product-images');

-- 7. INITIAL SEED DATASET (CATEGORIES & 10 SAMPLE SAREES WITH PRODUCT CODES)

INSERT INTO public.categories (id, name, slug, description, image_url) VALUES
(1, 'Cotton Sarees', 'cotton-sarees', 'Breathable, soft, and daily-wear handcrafted cotton sarees.', 'https://kuajhwywwvjykxjaaxkg.supabase.co/storage/v1/object/public/product-images/sarees/1.jpeg'),
(2, 'Silk Sarees', 'silk-sarees', 'Pure silk weaves with regal gold zari borders for grand occasions.', 'https://kuajhwywwvjykxjaaxkg.supabase.co/storage/v1/object/public/product-images/sarees/2.jpeg'),
(3, 'Banarasi Sarees', 'banarasi-sarees', 'Varanasi legacy brocade sarees rich with intricate flora motifs.', 'https://kuajhwywwvjykxjaaxkg.supabase.co/storage/v1/object/public/product-images/sarees/3.jpeg'),
(4, 'Daily Wear', 'daily-wear', 'Lightweight, elegant, everyday sarees engineered for comfort.', 'https://kuajhwywwvjykxjaaxkg.supabase.co/storage/v1/object/public/product-images/sarees/4.jpeg'),
(5, 'Wedding Sarees', 'wedding-sarees', 'Opulent Kanchipuram and Banarasi bridal heirloom collections.', 'https://kuajhwywwvjykxjaaxkg.supabase.co/storage/v1/object/public/product-images/sarees/8.jpeg')
ON CONFLICT (id) DO NOTHING;

INSERT INTO public.products (id, name, slug, description, category_id, price, compare_price, discount_percentage, fabric, color, occasion, stock, sku, main_image, is_active, is_featured) VALUES
('SAR-COT-001', 'Fancy Cotton Maroon Daily Saree', 'fancy-cotton-maroon-daily-saree', 'Elegant maroon pure cotton saree featuring floral block prints and a contrasting beige zari border.', 1, 899.00, 1299.00, 30, 'Cotton', 'Maroon', 'Daily Wear', 15, 'SAR-COT-001', 'https://kuajhwywwvjykxjaaxkg.supabase.co/storage/v1/object/public/product-images/sarees/1.jpeg', true, true),
('SAR-SLK-002', 'Royal Kanjivaram Soft Silk Saree', 'royal-kanjivaram-soft-silk-saree', 'Rich peacock blue soft silk saree with heavy gold brocade zari weave along the pallu and temple border motifs.', 2, 2499.00, 3999.00, 37, 'Silk', 'Blue', 'Wedding', 8, 'SAR-SLK-002', 'https://kuajhwywwvjykxjaaxkg.supabase.co/storage/v1/object/public/product-images/sarees/2.jpeg', true, true),
('SAR-BAN-003', 'Handwoven Banarasi Zari Silk Saree', 'handwoven-banarasi-zari-silk-saree', 'Traditional crimson red Banarasi silk saree featuring antique silver brocade motifs and hand-finished tassels.', 3, 3299.00, 4999.00, 34, 'Banarasi', 'Red', 'Wedding', 6, 'SAR-BAN-003', 'https://kuajhwywwvjykxjaaxkg.supabase.co/storage/v1/object/public/product-images/sarees/3.jpeg', true, true),
('SAR-GEO-004', 'Contemporary Georgette Printed Saree', 'contemporary-georgette-printed-saree', 'Lightweight pastel green georgette saree accented with micro-sequin border work and smooth flowy drape.', 4, 1199.00, 1699.00, 29, 'Georgette', 'Green', 'Office Wear', 20, 'SAR-GEO-004', 'https://kuajhwywwvjykxjaaxkg.supabase.co/storage/v1/object/public/product-images/sarees/4.jpeg', true, false),
('SAR-LIN-005', 'Pure Linen Handloom Mustard Saree', 'pure-linen-handloom-mustard-saree', 'Breathable organic linen saree in bright mustard yellow with silver tissue pallu and unstitched blouse piece.', 1, 1599.00, 2199.00, 27, 'Linen', 'Yellow', 'Daily Wear', 12, 'SAR-LIN-005', 'https://kuajhwywwvjykxjaaxkg.supabase.co/storage/v1/object/public/product-images/sarees/5.jpeg', true, true),
('SAR-CHN-006', 'Chanderi Silk Cotton Olive Saree', 'chanderi-silk-cotton-olive-saree', 'Lustrous olive green Chanderi silk saree with hand-woven gold zari motifs and lightweight sheen.', 2, 1899.00, 2599.00, 27, 'Silk', 'Green', 'Festive Celebration', 10, 'SAR-CHN-006', 'https://kuajhwywwvjykxjaaxkg.supabase.co/storage/v1/object/public/product-images/sarees/6.jpeg', true, true),
('SAR-TUS-007', 'Tussar Silk Hand Block Printed Saree', 'tussar-silk-hand-block-printed-saree', 'Authentic terracotta orange Tussar silk saree featuring traditional Ajrakh hand block prints and raw silk texture.', 2, 2199.00, 3199.00, 31, 'Soft Silk', 'Orange', 'Office Wear', 14, 'SAR-TUS-007', 'https://kuajhwywwvjykxjaaxkg.supabase.co/storage/v1/object/public/product-images/sarees/7.jpeg', true, false),
('SAR-KNJ-008', 'Kanjeevaram Bridal Ruby Red Saree', 'kanjeevaram-bridal-ruby-red-saree', 'Opulent ruby red Kanjeevaram pure silk saree with heavy gold brocade zari work across the body and pallu.', 5, 4599.00, 6999.00, 34, 'Silk', 'Red', 'Wedding', 5, 'SAR-KNJ-008', 'https://kuajhwywwvjykxjaaxkg.supabase.co/storage/v1/object/public/product-images/sarees/8.jpeg', true, true),
('SAR-ORG-009', 'Organza Floral Pastel Pink Saree', 'organza-floral-pastel-pink-saree', 'Delicate pastel pink sheer organza saree with hand-painted digital floral prints and embroidered pearl scalloped border.', 4, 1499.00, 1999.00, 25, 'Georgette', 'Pink', 'Festive Celebration', 18, 'SAR-ORG-009', 'https://kuajhwywwvjykxjaaxkg.supabase.co/storage/v1/object/public/product-images/sarees/9.jpeg', true, true),
('SAR-CHT-010', 'Chettinad Cotton Temple Border Saree', 'chettinad-cotton-temple-border-saree', 'Authentic Chettinad handloom cotton saree in deep navy and mustard with traditional rudraksham temple zari border.', 1, 999.00, 1499.00, 33, 'Cotton', 'Blue', 'Daily Wear', 25, 'SAR-CHT-010', 'https://kuajhwywwvjykxjaaxkg.supabase.co/storage/v1/object/public/product-images/sarees/10.jpeg', true, false)
ON CONFLICT (id) DO UPDATE SET main_image = EXCLUDED.main_image;

-- POPULATE GALLERY IMAGES TABLE
INSERT INTO public.product_images (product_id, image_url, display_order)
SELECT id, main_image, 1 FROM public.products
ON CONFLICT DO NOTHING;
